---
# In order to install/update contrib module, run followign command from root of project:
#        ansible-galaxy install -n -f -r contrib/requirements.yml --roles-path contrib
#
# Contrib requirements list.
#
- src: https://github.com/cibox/ansible-composer

# Jenkins 2
- src: karlmdavis.jenkins2

- src: geerlingguy.apache
  version: 2.0.0

- src: geerlingguy.memcached
  version: 1.0.7

- src: geerlingguy.mysql
  version: 2.5.0

- src: geerlingguy.php
  version: 3.4.2

- src: geerlingguy.php-pecl
  version: 1.3.0

- src: geerlingguy.php-xdebug
  version: 2.3.1

- src: geerlingguy.php-xhprof
  version: 2.2.0

# - src: https://github.com/cibox/ansible-php-pear
#  path: contrib

#- src: https://github.com/angstwad/docker.ubuntu
#  version: v1.1.8