
sudo: required
dist: trusty

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
 # Install Ansible.
  - sudo pip install ansible==2.2.0

before_script:
   - sudo apt-get purge mysql-server-5.6 mysql-common-5.6 mysql-client-5.6 mysql-server-core-5.6 mysql-client-core-5.6 && sudo rm -rf /var/lib/mysql && sudo apt-get autoremove && sudo apt-get autoclean

script:
   - ls -la
   - sudo ansible-playbook -vvvv services/jenkinsbox.yml -i 'localhost,' --connection=local --extra-vars="server_ip=127.0.0.1 mysql_root_password="
