server_ip: 127.0.0.1:2222
server_remote_user: ubuntu
# You can use docksal, drupalvm or cibox as local_environment.
local_environment: docksal
ansible_python_interpreter: "/usr/bin/python3"

# github_url: https://github.com/NAME/REPOSITORY
# Never put your own user as a bot, because you won't be able to get your PRs tested.
# github_username: BOT_NAME
# github_token: BOT_ACCESS_TOKEN
# github_password: BOT_PASSWORD