server_ip: d8cibox.ffwdeutschland.de:2210
github_url: https://github.com/ey-/d8_cibox
# Never put your own user as a bot, because you won't be able to get your PRs tested.
github_username: ffw-bot-de
github_token: ***************
github_password: "******"

jenkins_server_ip: d8cibox.ffwdeutschland.de
jenkins_admin_email: engin.yilmaz@ffwagency.com
