---
- name: restart jenkins
  become: true
  service: name=jenkins state=restarted

- name: configure default users
  become: true
  template:
    src: basic-security.groovy
    dest: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
  register: jenkins_users_config
