---
# This playbook should generates new project.
- hosts: 127.0.0.1
  connection: local
  gather_facts: no

  vars:
    cmf: drupal
    repo_subfolder: ../d8_cibox
    drupal_version: 8
    composer_workflow: true

  roles:
      - { role: '../core/core-repository' }
