---
# Trick from http://stackoverflow.com/a/30953269
- name: Copy groovy script
  template:
    src: scripts/encrypt.groovy.j2
    dest: '{{ jenkins_home }}/encrypt.groovy'
    owner: root
    group: root
    mode: 0755
    force: yes

#- name: Encrypt GitHub password
#  become: yes
#  action: command java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }} groovy {{ jenkins_home }}/encrypt.groovy --username {{ jenkins_admin_username }} --password {{ jenkins_admin_password }}
#  register: encrypted_pass
#  notify: restart jenkins
#
#- name: Set encrypted password
#  set_fact: github_encrypted_password="{{ encrypted_pass.stdout }}"

- name: Remove groovy script
  file:
    path: '{{ jenkins_home }}/encrypt.groovy'
    state: absent

- name: Create folders for Jenkins jobs
  file:
    path: /var/lib/jenkins/jobs/{{ item.name }}
    state: directory
    owner: jenkins
    group: jenkins
  when: item.status == true
  with_items: "{{ jenkins_jobs }}"

- name: Copy Jenkins jobs
  template:
    src: jobs/{{ item.template }}
    dest: /var/lib/jenkins/jobs/{{ item.name }}/config.xml
    owner: jenkins
    group: jenkins
    force: yes
  notify: restart jenkins
  when: item.status == true
  with_items: "{{ jenkins_jobs }}"

# Automatically scan users directory.
#- name: Create folders for users
#  file:
#    path: /var/lib/jenkins/users/{{ item.name }}
#    state: directory
#    owner: jenkins
#    group: jenkins
#  when: item.status == true
#  with_items: "{{ jenkins_users }}"

#- name: Copy user configs
#  template:
#    src: users/{{ item.template }}
#    dest: /var/lib/jenkins/users/{{ item.name }}/config.xml
#    owner: jenkins
#    group: jenkins
#    mode: 0755
#    force: yes
#  notify: Restart Jenkins
#  when: item.status == true
#  with_items: "{{ jenkins_users }}"

# Automatically scan configs directory.
#- name: Copy Jenkins configs
#  template:
#    src: configs/{{ item | basename }}
#    dest: /var/lib/jenkins/{{ item | basename | regex_replace('\.j2','') }}
#    owner: jenkins
#    group: jenkins
#    force: yes
#  notify: restart jenkins
#  with_fileglob:
#    - ../templates/configs/*.j2

- name: Create folder for htaccess file for jenkins
  file:
    path: /etc/htpasswd
    state: directory

- name: Create htpasswd file for jenkins
  htpasswd:
    path: /etc/htpasswd/.jenkins
    name: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    owner: root
    group: www-data
    mode: 0640